### ISSUE TITLE
Recommend changing settings needed when deploying publicly 

### ISSUE THREAD

**Issue by Alisa-Modeste** [kudelskisecurity/fumblechain#2]
Previous:
Also make sure to set IS_DOCKER_LOCAL to 0 when deploying the CTF publicly so that it works for clients who connect from another machine.

Change to:
Also make sure to set IS_DOCKER_LOCAL to 0 and HOST_BIND_ADDRESS to 0.0.0.0 or your machine's IP address when deploying the CTF publicly so that it works for clients who connect from another machine.

**Comment by amietn** [comment]
Thank you, this should be fixed in https://github.com/kudelskisecurity/fumblechain/commit/65982c9247b7228d4b77f7937ea5ef4bca347490
