### ISSUE TITLE
Fix for the moneymaker account not sending coins

### ISSUE THREAD

**Issue by Alisa-Modeste** [kudelskisecurity/fumblechain#3]
On the fumblestore branch, line 4 of daemon.sh says `source ctf_wallet_addresses.bash` the location is actually `source gen/ctf_wallet_addresses.bash`

**Comment by amietn** [comment]
I believe this is the intended behavior.

The file `gen/ctf_wallet_addresses.bash` is copied to the correct location inside the .tar.gz archive that is generated in `docker/fumblestore/Dockerfile`: https://github.com/kudelskisecurity/fumblechain/blob/f6bf9815ca0de399fdba8ebb2f31b8679ec25471/src/fumblechain/docker/fumblestore/Dockerfile#L13

So, when someone downloads the .tar.gz archive in challenge1, the file inside will be located at the expected location and not in the `gen` directory.

**Comment by Alisa-Modeste** [comment]
Hmm. I just made a new clone. When I ran the fc-docker.sh command, I got

> Successfully tagged fc:latest
> ./daemon.sh: line 4: ctf_wallet_addresses.bash: No such file or directory

**Comment by Alisa-Modeste** [comment]
The full command and output:

./fc-docker.sh -p 2223 -n fc-testnet -i fc -P 1338 -E 20602 -H demo.fumblechain.io:20701 --magic=808811
Sending build context to Docker daemon  7.664MB
Step 1/7 : FROM python:3.7-alpine
 ---> 930a7e894675
Step 2/7 : RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev bash git
 ---> Using cache
 ---> 30eaa1e56163
Step 3/7 : COPY requirements.txt .
 ---> Using cache
 ---> 43ad9187906b
Step 4/7 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> d098a9ca45c9
Step 5/7 : WORKDIR /opt/fumblechain
 ---> Using cache
 ---> 6e58e996bc7d
Step 6/7 : COPY . .
 ---> Using cache
 ---> c7b7f480bf32
Step 7/7 : CMD ./daemon.sh
 ---> Using cache
 ---> 5ef3c378df10
Successfully built 5ef3c378df10
Successfully tagged fc:latest
./daemon.sh: line 4: ctf_wallet_addresses.bash: No such file or directory

**Comment by amietn** [comment]
That's interesting. Did you run run `fc-docker.sh` directly from within the git repository?

The way it is meant to be executed is:

* Browse the fumblestore (either the live demo or your own instance)
* Browse the first challenge page
* Download the .tar.gz client and extract it
* Execute the `fc-docker.sh` script that was within that .tar.gz archive, not the one in the git repository

Could you describe what you did before executing `fc-docker.sh`?

EDIT: I meant `fc-docker.sh`, not `daemon.sh`

**Comment by Alisa-Modeste** [comment]
Ah. I see what you're saying. Okay, then there shouldn't be a problem
